name: maiden_employer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cached_network_image: ^3.2.1
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^6.0.0
  dio: ^4.0.6
  expandable: ^5.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.5
  get_storage: ^2.0.3
  get: 4.6.5
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2

  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/

  fonts: 
    - family: Century-Gothic
      fonts: 
        - asset: assets/fonts/Century-Gothic.ttf
          weight: 500
        - asset: assets/fonts/Century-Gothic-Bold.ttf
          weight: 700
    - family: SF-Pro
      fonts: 
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-UltraLight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 100