name: maiden_employer
version: 1.0.0+3
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.5
  get: 4.6.5
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  flutter_secure_storage: ^6.0.0
  fluttertoast: ^8.1.1

  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/

  fonts: 
    - family: Century-Gothic
      fonts: 
        - asset: assets/fonts/Century-Gothic.ttf
        
    - family: SF-Pro
      fonts: 
        - asset: assets/fonts/SF-Pro-Display-Regular.otf