name: maiden_employer
version: 1.0.0+9
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.6
  get: 4.6.5
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  flutter_secure_storage: ^6.1.0
  fluttertoast: ^8.1.1
  flutter_typeahead: ^4.3.1
  flutter_rating_bar: ^4.0.1
  expandable: ^5.0.1
  path_provider: ^2.0.11
  flutter_pdfview: ^1.2.5
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  flutter_spinkit: ^5.1.0
  table_calendar: ^3.0.8


  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/

  fonts: 
    - family: Century-Gothic
      fonts: 
        - asset: assets/fonts/Century-Gothic.ttf
        
    - family: SF-Pro
      fonts: 
        - asset: assets/fonts/SF-Pro-Display-Regular.otf